[tool.poetry]
name = "example-flask-restx"
version = "0.1.0"
description = ""
authors = ["Rhinoj0sa <rhinojosaram@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
